#pragma once

#define WINDOW_WIDTH 1920
#define WINDOW_HEIGHT 1080

#define	DESTROY_INACTIVE_TIMERS_DURING_RUNTIME true
#define DESTROY_EMPTY_SCENES_DURING_RUNTIME false
#define DESTROY_GAMEOBJECTS_DURING_RUNTIME true
#define CALL_OBJECT_CLEANUP_BY_TIMER true
